jdbt:
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('LOCAL_DUCKDB_PATH') }}"
      threads: 1
    prod:
      type: databricks
      catalog: test
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "/sql/1.0/warehouses/333120755706219a"
      schema: main
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      auth_type: databricks_cli
      # auth_type: oauth

  target: "{{ 'local' if env_var('DAGSTER_ENV') == 'LOCAL' else 'prod' }}"