version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  sync:
    desc: "Sync project environment. Usage: task project -- <folder>"
    dir: "{{.CLI_ARGS}}"
    cmds:
      - uv sync
    preconditions:
      - sh: 'test -n "{{.CLI_ARGS}}"'
        msg: "Error: <folder> argument is required. Example: task project -- dbx-project"


  sync-all:
    desc: "Sync all projects and install all dependencies. Usage: task sync-all -- <folder>"
    dir: "{{.CLI_ARGS}}"
    cmds:
      - uv sync --all-packages --all-groups
    preconditions:
      - sh: 'test -n "{{.CLI_ARGS}}"'
        msg: "Error: <folder> argument is required. Example: task sync-all -- dbt-cloud-orchestration"


  dg-dev:
    desc: "Run Dagster dev server. Usage: task dg-dev -- <folder>"
    cmds:
      - task: sync
        vars: {CLI_ARGS: '{{.CLI_ARGS}}'}
      - 'if [ -f workspace.yaml ]; then dg dev --workspace workspace.yaml; else dg dev; fi'
    dir: "{{.CLI_ARGS}}"
    preconditions:
      - {sh: 'test -n "{{.CLI_ARGS}}"', msg: "Error: <folder> argument is required. Example: task dg-dev -- dbx-project"}

  dgdev:
    desc: "Run Dagster dev server from current folder"
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - 'uv sync --all-packages --all-groups'
      - 'if [ -f workspace.yaml ]; then dg dev --workspace workspace.yaml; else dg dev; fi'

  pg-prepare:
    desc: "Setup PostgreSQL and load data"
    dir: "sling-project"
    cmds:
      - createdb jaffle_shop || true
      - sling conns set POSTGRES_CONN url="postgresql://localhost:5432/jaffle_shop?sslmode=disable"
      - sling run --src-conn "file://data/raw_customers.csv" --tgt-conn POSTGRES_CONN --tgt-object public.raw_customers
      - sling run --src-conn "file://data/raw_orders.csv" --tgt-conn POSTGRES_CONN --tgt-object public.raw_orders
      - sling run --src-conn "file://data/raw_payments.csv" --tgt-conn POSTGRES_CONN --tgt-object public.raw_payments

  pg-cli:
    desc: "Open PostgreSQL CLI for jaffle_shop"
    cmds:
      - psql -h localhost -d jaffle_shop

  ddb:
    desc: "Start DuckDB UI in dbx-project"
    dir: "dbx-project"
    cmds:
      - duckdb /tmp/jaffle_platform.duckdb -cmd "INSTALL ui; LOAD ui;" -ui

  test:
    desc: "Run pytest in a project. Usage: task test -- <folder> (defaults to current folder)"
    dir: "{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}{{.USER_WORKING_DIR}}{{end}}"
    cmds:
      - uv run pytest -v
